spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #euerka服务自动注册进router
          enabled: true
          #服务名路径小写
          lowerCaseServiceId: true
          predicates:
            #这是原来默认的断言
            - name: Path
              args:
                pattern: "'/'+serviceId+'/**'"
          filters:
            #这是原来默认的替换路径filter
#            - name: RewritePath
#              args:
#                regexp: "'/' + serviceId + '/?(?<remaining>.*)'"
#                replacement: "'/${remaining}'"
            #我们子模块都自带basePath，走路由需要删除模块的第一个'/'前缀
            - name: StripPrefix
              args:
                parts: 1
            #路径增加模块名为前缀
            - name: PrefixPath
              args:
                prefix: "'/' + serviceId"

server:
  port: @service.port@

#监控，访问路径 {ip}:{port}/actuator
management:
  server:
    #    base-path: /${spring.application.name}/actuator
    port: @service.management.port@
  health:
    elasticsearch:
      enabled: false


logging:
  file:
    path: @ce.log.base.dir@/${spring.application.name}
  config: classpath:logback-spring.xml

ce:
  datasource:
    hikari:
      #修改数据库连接池线程数
      maximum-pool-size: 1


quartz:
  enabled: false
  scheduler-name: gatewayScheduler

eureka:
  instance:
    metadata-map:
      order: 0
      name_zh-cn: 网关
      name_zh-tw: 網關
      name_en: Gateway
      basePath: /
      icon: gateway

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: management-center
        url: /management-center/v3/api-docs
      - name: vm-service
        url: /vm-service/v3/api-docs
      - name: finance-management
        url: /finance-management/v3/api-docs
      - name: operation-analysis
        url: /operation-analysis/v3/api-docs
      - name: security-compliance
        url: /security-compliance/v3/api-docs

